volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge

services:
  frontend:
    container_name: frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=http://localhost:8080
    ports:
      - "3000:3000"
    networks:
      - app-network

  db:
    container_name: postgresdb
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    networks:
      - app-network

  app:
    container_name: javadev
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    env_file:
      - ../.env
#       -.env
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network
